package cn.edu.xust.mapper;

import cn.edu.xust.bean.AmmeterParameter;
import org.springframework.stereotype.Repository;

/**
 * @author Huangxin
 * @since Mon Mar 23 22:42:29 CST 2020
 */
@Repository(value = "ammeterParamMapper")
public interface AmmeterParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ammeter_parameter
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    int insert(AmmeterParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ammeter_parameter
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    int insertSelective(AmmeterParameter record);

    /**
     * 更新非空字段信息
     *
     * @return
     */
    int updateSelective(AmmeterParameter record);
}