package cn.edu.xust.mapper;

import cn.edu.xust.bean.ElectricMeter;

public interface ElectricMeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electric_meter
     *
     * @mbg.generated Thu Feb 20 18:11:23 CST 2020
     */
    int deleteByPrimaryKey(Integer electricMeterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electric_meter
     *
     * @mbg.generated Thu Feb 20 18:11:23 CST 2020
     */
    int insert(ElectricMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electric_meter
     *
     * @mbg.generated Thu Feb 20 18:11:23 CST 2020
     */
    int insertSelective(ElectricMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electric_meter
     *
     * @mbg.generated Thu Feb 20 18:11:23 CST 2020
     */
    ElectricMeter selectByPrimaryKey(Integer electricMeterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electric_meter
     *
     * @mbg.generated Thu Feb 20 18:11:23 CST 2020
     */
    int updateByPrimaryKeySelective(ElectricMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electric_meter
     *
     * @mbg.generated Thu Feb 20 18:11:23 CST 2020
     */
    int updateByPrimaryKey(ElectricMeter record);
}