package cn.edu.xust.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author Huangxin
 */
public class AmmeterParameter implements Serializable {

    /**每个消息的唯一标志*/
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.telec_id
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Integer telecId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.device_number
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private String deviceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.acq_time
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Date acqTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_a_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentAVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_b_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentBVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_c_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentCVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_a_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentACurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_b_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentBCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_c_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentCCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentActivePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_reactive_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentReactivePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_power_factor
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentPowerFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_positive_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentPositiveActivePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_negtive_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentNegtiveActivePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.current_total_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private Double currentTotalActivePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ammeter_parameter.ammeter_status
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    private String ammeterStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.telec_id
     *
     * @return the value of ammeter_parameter.telec_id
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Integer getTelecId() {
        return telecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.telec_id
     *
     * @param telecId the value for ammeter_parameter.telec_id
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setTelecId(Integer telecId) {
        this.telecId = telecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.device_number
     *
     * @return the value of ammeter_parameter.device_number
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.device_number
     *
     * @param deviceNumber the value for ammeter_parameter.device_number
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber == null ? null : deviceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.acq_time
     *
     * @return the value of ammeter_parameter.acq_time
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Date getAcqTime() {
        return acqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.acq_time
     *
     * @param acqTime the value for ammeter_parameter.acq_time
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setAcqTime(Date acqTime) {
        this.acqTime = acqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_a_Voltage
     *
     * @return the value of ammeter_parameter.current_a_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentAVoltage() {
        return currentAVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_a_Voltage
     *
     * @param currentAVoltage the value for ammeter_parameter.current_a_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentAVoltage(Double currentAVoltage) {
        this.currentAVoltage = currentAVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_b_Voltage
     *
     * @return the value of ammeter_parameter.current_b_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentBVoltage() {
        return currentBVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_b_Voltage
     *
     * @param currentBVoltage the value for ammeter_parameter.current_b_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentBVoltage(Double currentBVoltage) {
        this.currentBVoltage = currentBVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_c_Voltage
     *
     * @return the value of ammeter_parameter.current_c_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentCVoltage() {
        return currentCVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_c_Voltage
     *
     * @param currentCVoltage the value for ammeter_parameter.current_c_Voltage
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentCVoltage(Double currentCVoltage) {
        this.currentCVoltage = currentCVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_a_current
     *
     * @return the value of ammeter_parameter.current_a_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentACurrent() {
        return currentACurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_a_current
     *
     * @param currentACurrent the value for ammeter_parameter.current_a_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentACurrent(Double currentACurrent) {
        this.currentACurrent = currentACurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_b_current
     *
     * @return the value of ammeter_parameter.current_b_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentBCurrent() {
        return currentBCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_b_current
     *
     * @param currentBCurrent the value for ammeter_parameter.current_b_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentBCurrent(Double currentBCurrent) {
        this.currentBCurrent = currentBCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_c_current
     *
     * @return the value of ammeter_parameter.current_c_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentCCurrent() {
        return currentCCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_c_current
     *
     * @param currentCCurrent the value for ammeter_parameter.current_c_current
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentCCurrent(Double currentCCurrent) {
        this.currentCCurrent = currentCCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_active_power
     *
     * @return the value of ammeter_parameter.current_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentActivePower() {
        return currentActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_active_power
     *
     * @param currentActivePower the value for ammeter_parameter.current_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentActivePower(Double currentActivePower) {
        this.currentActivePower = currentActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_reactive_power
     *
     * @return the value of ammeter_parameter.current_reactive_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentReactivePower() {
        return currentReactivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_reactive_power
     *
     * @param currentReactivePower the value for ammeter_parameter.current_reactive_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentReactivePower(Double currentReactivePower) {
        this.currentReactivePower = currentReactivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_power_factor
     *
     * @return the value of ammeter_parameter.current_power_factor
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentPowerFactor() {
        return currentPowerFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_power_factor
     *
     * @param currentPowerFactor the value for ammeter_parameter.current_power_factor
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentPowerFactor(Double currentPowerFactor) {
        this.currentPowerFactor = currentPowerFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_positive_active_power
     *
     * @return the value of ammeter_parameter.current_positive_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentPositiveActivePower() {
        return currentPositiveActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_positive_active_power
     *
     * @param currentPositiveActivePower the value for ammeter_parameter.current_positive_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentPositiveActivePower(Double currentPositiveActivePower) {
        this.currentPositiveActivePower = currentPositiveActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_negtive_active_power
     *
     * @return the value of ammeter_parameter.current_negtive_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentNegtiveActivePower() {
        return currentNegtiveActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_negtive_active_power
     *
     * @param currentNegtiveActivePower the value for ammeter_parameter.current_negtive_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentNegtiveActivePower(Double currentNegtiveActivePower) {
        this.currentNegtiveActivePower = currentNegtiveActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.current_total_active_power
     *
     * @return the value of ammeter_parameter.current_total_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public Double getCurrentTotalActivePower() {
        return currentTotalActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.current_total_active_power
     *
     * @param currentTotalActivePower the value for ammeter_parameter.current_total_active_power
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setCurrentTotalActivePower(Double currentTotalActivePower) {
        this.currentTotalActivePower = currentTotalActivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ammeter_parameter.ammeter_status
     *
     * @return the value of ammeter_parameter.ammeter_status
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public String getAmmeterStatus() {
        return ammeterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ammeter_parameter.ammeter_status
     *
     * @param ammeterStatus the value for ammeter_parameter.ammeter_status
     *
     * @mbg.generated Mon Mar 23 22:42:29 CST 2020
     */
    public void setAmmeterStatus(String ammeterStatus) {
        this.ammeterStatus = ammeterStatus == null ? null : ammeterStatus.trim();
    }
}